micronaut:
  application:
    name: profile
  server:
    port: 3222
  security:
    reject-not-found: false
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:test}"'
